/*
 * Copyright (C) 2014 Michael Pardo
 * Copyright (C) 2014 Niek Haarman
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.nhaarman.ellie.internal;

import com.nhaarman.ellie.Model;

import org.jetbrains.annotations.NotNull;

/**
 * Used internally for model definitions.
 *
 * Subclasses of this interface are typically generated by the compiler module,
 * and accessible using the generated {@link AdapterHolder}.
 */
public interface ModelAdapter<T extends Model> {

    /**
     * Returns the type of the Model.
     *
     * @return The type Class.
     */
    @NotNull
    Class<T> getModelType();

    /**
     * Returns the name of the table.
     *
     * @return The name of the table.
     */
    @NotNull
    String getTableName();

    /**
     * Returns the executable SQL statements used to create the table.
     *
     * @return The executable SQL statements.
     */
    @NotNull
    String getSchema();

}