language: android

jdk: oraclejdk8

script:
 - ./gradlew clean test assemble --stacktrace

after_success:
  - if [[ $TRAVIS_BRANCH == 'dev' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./gradlew uploadArchives -PNEXUS_USERNAME=$NEXUS_USERNAME -PNEXUS_PASSWORD=$NEXUS_PASSWORD ; fi

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4a9094212020b1f7a094
    on_success: change
    on_failure: change
    on_start: false
